device_interfaces_details={'interface': {'FortyGigabitEthernet2/1/1': {'interface_is_ok': 'YES',
                                             'ip_address': 'unassigned',
                                             'method': 'unset',
                                             'protocol': 'down',
                                             'status': 'down'},
               'FortyGigabitEthernet2/1/2': {'interface_is_ok': 'YES',
                                             'ip_address': 'unassigned',
                                             'method': 'unset',
                                             'protocol': 'down',
                                             'status': 'down'},
               'FortyGigabitEthernet2/1/3': {'interface_is_ok': 'YES',
                                             'ip_address': 'unassigned',
                                             'method': 'unset',
                                             'protocol': 'down',
                                             'status': 'down'},
               'FortyGigabitEthernet2/1/4': {'interface_is_ok': 'YES',
                                             'ip_address': 'unassigned',
                                             'method': 'unset',
                                             'protocol': 'down',
                                             'status': 'down'},
               'GigabitEthernet0/0': {'interface_is_ok': 'YES',
                                      'ip_address': '10.10.20.66',
                                      'method': 'NVRAM',
                                      'protocol': 'up',
                                      'status': 'up'},
               'GigabitEthernet1/0/1': {'interface_is_ok': 'YES',
                                        'ip_address': '192.168.1.1',
                                        'method': 'manual',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/2': {'interface_is_ok': 'YES',
                                        'ip_address': '10.0.0.5',
                                        'method': 'other',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/3': {'interface_is_ok': 'YES',
                                        'ip_address': '10.20.60.1',
                                        'method': 'manual',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/4': {'interface_is_ok': 'YES',
                                        'ip_address': '10.20.40.1',
                                        'method': 'manual',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/5': {'interface_is_ok': 'YES',
                                        'ip_address': '10.40.0.1',
                                        'method': 'manual',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/6': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/7': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet1/0/8': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'up',
                                        'status': 'up'},
               'GigabitEthernet3/0/1': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/10': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/11': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/12': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/13': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/14': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/15': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/16': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/17': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/18': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/19': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/2': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/20': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/21': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/22': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/23': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/24': {'interface_is_ok': 'YES',
                                         'ip_address': 'unassigned',
                                         'method': 'unset',
                                         'protocol': 'down',
                                         'status': 'down'},
               'GigabitEthernet3/0/3': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/4': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/5': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/6': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/7': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/8': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/0/9': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/1/1': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/1/2': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/1/3': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'GigabitEthernet3/1/4': {'interface_is_ok': 'YES',
                                        'ip_address': 'unassigned',
                                        'method': 'unset',
                                        'protocol': 'down',
                                        'status': 'down'},
               'Loopback1': {'interface_is_ok': 'YES',
                             'ip_address': '10.100.1.1',
                             'method': 'other',
                             'protocol': 'up',
                             'status': 'up'},
               'Loopback10': {'interface_is_ok': 'YES',
                              'ip_address': '10.10.10.1',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'Loopback100': {'interface_is_ok': 'YES',
                               'ip_address': '192.168.100.1',
                               'method': 'manual',
                               'protocol': 'up',
                               'status': 'up'},
               'Loopback101': {'interface_is_ok': 'YES',
                               'ip_address': '10.200.101.1',
                               'method': 'manual',
                               'protocol': 'up',
                               'status': 'up'},
               'Loopback11': {'interface_is_ok': 'YES',
                              'ip_address': '10.10.11.1',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'Loopback123': {'interface_is_ok': 'YES',
                               'ip_address': '10.123.123.123',
                               'method': 'manual',
                               'protocol': 'up',
                               'status': 'up'},
               'Loopback2': {'interface_is_ok': 'YES',
                             'ip_address': '10.100.2.2',
                             'method': 'other',
                             'protocol': 'up',
                             'status': 'up'},
               'Loopback20': {'interface_is_ok': 'YES',
                              'ip_address': '10.20.20.20',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'Loopback21': {'interface_is_ok': 'YES',
                              'ip_address': '10.21.21.21',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'Loopback321': {'interface_is_ok': 'YES',
                               'ip_address': '66.66.66.66',
                               'method': 'other',
                               'protocol': 'up',
                               'status': 'up'},
               'Loopback90': {'interface_is_ok': 'YES',
                              'ip_address': '10.90.90.1',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'Loopback91': {'interface_is_ok': 'YES',
                              'ip_address': '10.91.91.1',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'Loopback99': {'interface_is_ok': 'YES',
                              'ip_address': '192.168.99.1',
                              'method': 'manual',
                              'protocol': 'up',
                              'status': 'up'},
               'TenGigabitEthernet2/0/1': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/10': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/11': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/12': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/13': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/14': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/15': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/16': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/17': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/18': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/19': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/2': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/20': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/21': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/22': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/23': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/24': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/25': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/26': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/27': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/28': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/29': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/3': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/30': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/31': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/32': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/33': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/34': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/35': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/36': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/37': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/38': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/39': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/4': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/40': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/41': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/42': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/43': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/44': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/45': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/46': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/47': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/48': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/0/5': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/6': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/7': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/8': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/0/9': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/1': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/10': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/11': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/12': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/13': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/14': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/15': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/16': {'interface_is_ok': 'YES',
                                            'ip_address': 'unassigned',
                                            'method': 'unset',
                                            'protocol': 'down',
                                            'status': 'down'},
               'TenGigabitEthernet2/1/2': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/3': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/4': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/5': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/6': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/7': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/8': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet2/1/9': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet3/1/1': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet3/1/2': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet3/1/3': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'TenGigabitEthernet3/1/4': {'interface_is_ok': 'YES',
                                           'ip_address': 'unassigned',
                                           'method': 'unset',
                                           'protocol': 'down',
                                           'status': 'down'},
               'Vlan1': {'interface_is_ok': 'YES',
                         'ip_address': 'unassigned',
                         'method': 'NVRAM',
                         'protocol': 'down',
                         'status': 'up'},
               'Vlan10': {'interface_is_ok': 'YES',
                          'ip_address': '192.168.10.1',
                          'method': 'manual',
                          'protocol': 'up',
                          'status': 'up'},
               'Vlan100': {'interface_is_ok': 'YES',
                           'ip_address': 'unassigned',
                           'method': 'unset',
                           'protocol': 'down',
                           'status': 'administratively down'},
               'Vlan1104': {'interface_is_ok': 'YES',
                            'ip_address': 'unassigned',
                            'method': 'unset',
                            'protocol': 'down',
                            'status': 'down'},
               'Vlan122': {'interface_is_ok': 'YES',
                           'ip_address': 'unassigned',
                           'method': 'unset',
                           'protocol': 'down',
                           'status': 'down'},
               'Vlan20': {'interface_is_ok': 'YES',
                          'ip_address': '192.168.20.1',
                          'method': 'manual',
                          'protocol': 'down',
                          'status': 'up'},
               'Vlan35': {'interface_is_ok': 'YES',
                          'ip_address': '192.168.35.1',
                          'method': 'manual',
                          'protocol': 'up',
                          'status': 'up'}}}

device_vlan_details=[{'interfaces': [], 'status': 'active', 'vlan_id': '1', 'vlan_name': 'default'},
                            {'interfaces': [],
                            'status': 'active',
                            'vlan_id': '2',
                            'vlan_name': 'VLAN0002'},
                            {'interfaces': ['Gi1/0/8'],
                            'status': 'active',
                            'vlan_id': '10',
                            'vlan_name': 'USERS'},
                            {'interfaces': [],
                            'status': 'active',
                            'vlan_id': '20',
                            'vlan_name': 'FINANCE'},
                            {'interfaces': [], 'status': 'active', 'vlan_id': '30', 'vlan_name': 'VOICE'},
                            {'interfaces': [], 'status': 'active', 'vlan_id': '35', 'vlan_name': 'Lab'},
                            {'interfaces': [], 'status': 'active', 'vlan_id': '40', 'vlan_name': 'BPO'},
                            {'interfaces': [],
                            'status': 'active',
                            'vlan_id': '50',
                            'vlan_name': 'Interns'},
                            {'interfaces': [],
                            'status': 'active',
                            'vlan_id': '100',
                            'vlan_name': 'Engineering'},
                            {'interfaces': ['Gi1/0/6'],
                            'status': 'active',
                            'vlan_id': '200',
                            'vlan_name': 'Marketing'},
                            {'interfaces': [], 'status': 'active', 'vlan_id': '300', 'vlan_name': 'HR'},
                            {'interfaces': [],
                            'status': 'active',
                            'vlan_id': '333',
                            'vlan_name': 'test_vlan_created_by_rishav'},
                            {'interfaces': [],
                            'status': 'active',
                            'vlan_id': '500',
                            'vlan_name': 'Test_vlan'},
                            {'interfaces': [],
                            'status': 'act/unsup',
                            'vlan_id': '1002',
                            'vlan_name': 'fddi-default'},
                            {'interfaces': [],
                            'status': 'act/unsup',
                            'vlan_id': '1003',
                            'vlan_name': 'token-ring-default'},
                            {'interfaces': [],
                            'status': 'act/unsup',
                            'vlan_id': '1004',
                            'vlan_name': 'fddinet-default'},
                            {'interfaces': [],
                            'status': 'act/unsup',
                            'vlan_id': '1005',
                            'vlan_name': 'trnet-default'}]